services:
  postgres:
    image: postgres:15
    container_name: price-db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile.flask
    container_name: flask-container
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile.airflow
    container_name: airflow-container
    restart: always
    env_file:
      - .env     # <-- Utilisation du même .env à la racine
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    command: >
      bash -c "airflow db upgrade &&
             airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
             airflow scheduler & airflow webserver"
volumes:
  pgdata:
